name: Build Document
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build-document:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Build document
      uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "."
        build-command: "sphinx-build -b html . _build"
